spring.application.name=LaptechBE

server.port=8080
server.address=localhost

spring.data.mongodb.uri=mongodb+srv://21522185:TQKhai21522185@cluster0.87r1let.mongodb.net/Laptech?retryWrites=true&w=majority
spring.data.mongodb.database=Laptech

server.servlet.session.cookie.same-site=strict
spring.data.mongodb.auto-index-creation=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=21522185@gm.uit.edu.vn
spring.mail.password=wzvkzrfppnbuxtvw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8